app:
  name: onix
  version: 1.0.1
build:
  entry: src/main.rs
  command: cargo build --release
  output_name: onix
targets:
- os: linux
  arch: amd64
- os: linux
  arch: arm64
- os: macos
  arch: arm64
- os: windows
  arch: amd64
install:
  file-type: binary
  target-dir: ~/.local/bin
  bin-name: onix
permissions:
- type: filesystem
  action: write
  path: ~/.local/bin
  variable: null
- type: environment
  action: modify
  path: null
  variable: PATH
