app:
  name: onix
  version: 0.1.3
build:
  entry: src/main.rs
  command: cargo build --release
  output_name: onix
targets:
- os: linux
  arch: x86_64
- os: macos
  arch: x86_64
- os: macos
  arch: arm64
- os: windows
  arch: x86_64
install:
  file_type: binary
  target_dir: C:\onix
  bin_name: onix
permissions:
- type: filesystem
  action: write
  path: C:\onix
  variable: null
- type: environment
  action: modify
  path: null
  variable: PATH
